import type { Metadata } from "next";
import "./globals.css";
import NavConductor from "./_nav-components/NavConductor";
import Aside from "./_layout-components/Aside";

export const metadata: Metadata = {
  title: "Queer women rep",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavConductor/>
        <Aside />
        {children}
        </body>
    </html>
  );
}
